### ISSUE TITLE
CustomEntityType.php no longer exists in latest version.

### ISSUE THREAD

**Issue by kimpellikaan** [akeneo-labs/CustomEntityBundle#106]
In https://docs.akeneo.com/master/design_pim/guides/create_a_reference_data_crud.html#creating-the-form-type-for-creation-and-edition you are referring to `use Pim\Bundle\CustomEntityBundle\Form\Type\CustomEntityType`. Only the class not longer exists.

**Comment by jmleroux** [comment]
Hello @kimpellikaan ,
indeed, the documentation is not up to date. We need to raise a ticket on the [PIM documentation project](https://github.com/akeneo/pim-docs) to synchronize the doc.

**Comment by kevinrademan** [comment]
Is the symfony forms still supported at all, or will any custom entities built in V1.7 have to be migrated to the forms extensions approach?

**Comment by jmleroux** [comment]
Currently, we encourage and recommend the form extension approach.
But i could study a community PR to add the support of SF forms.

**Comment by kevinrademan** [comment]
Thanks for the quick response, I think the forms extensions approach is much better (and more modern). 
I've been working to convert the forms over, and the following problem is why I was investigating if symfony forms was still supported. 

In the previous module with symfony forms you had a mechanism in place where referenced entries would display as a dropdown in the forms. 

I see that there is a select field which I assume would be used to create the referenced dropdowns
vendor\akeneo\pim-community-dev\src\Pim\Bundle\EnrichBundle\Resources\public\js\form\common\fields\select.js

The only part I'm struggling to piece together is how in the create.yml or edit.yml I would load the options from a repository?

```
pim-retailer-edit-form-properties-reservationAvailable:
        module: pim/form/common/fields/select
        parent: pim-retailer-edit-form-properties-common
        targetZone: content
        position: 150
        config:
            fieldName: association
            required: false
            readOnly: false
            choices: 'WHAT_SHOULD_GO_HERE?'
            multiple: false
```

**Comment by kevinrademan** [comment]
I've managed to come up with a solution to this problem which I think is withing the design pattern of the custom entity module.

https://github.com/kevinrademan/CustomEntityBundle/commit/782be1aa16da0336405944f9b6d05f02f053eb60

What I've done is the following
1. I created a custom select control which which uses configurations from the from extensions to load the custom values client side using the FetcherRegistry

In order to get this working I had to create a new rest action called GetAll which allows us to load all the custom entities using a rest endpoint (In future this should probably also support paging and the search functionality). Adding a new rest action means extending and changing quite a few files to correctly wire it in. You can check my commit for all the touch points. 

2. In order to support multi select associations (so many to many relationships), I needed to extend the Updater.php with some special code to correctly load all the entries into a array.

My commit doesn't show how the form extensions look, so I've included a snippet here

Custom entity that supports single select
```
pim-retailer-edit-form-properties-association:
        module: custom_entity/field/custom-entity-select
        parent: pim-retailer-edit-form-properties-common
        targetZone: content
        position: 270
        config:
            fieldName: association
            choiceNameField: code
            choiceValueField: name
            isCustomEntity: true
            entityName: association
            required: false
```


Custom entity that supports multi select
```
pim-retailer-edit-form-properties-paymenttypes:
        module: custom_entity/field/custom-entity-select
        parent: pim-retailer-edit-form-properties-common
        targetZone: content
        position: 280
        config:
            fieldName: paymentTypes
            choiceNameField: code
            choiceValueField: name
            isCustomEntity: true
            entityName: paymenttype
            required: false
            isMultiple: true
```

Field on a custom entity that refers to a built in akeneo type (special usecase for us)
```
pim-entity-edit-form-properties-attribute:
        module: custom_entity/field/custom-entity-select
        parent: pim-entity-edit-form-properties-common
        targetZone: content
        position: 270
        config:
            fieldName: attribute
            choiceNameField: code
            choiceValueField: name
            isCustomEntity: false
            entityName: attribute
            required: false
```
