### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by simoncarre** [akeneo-labs/CustomEntityBundle#124]
Hi!

I'm using the bundle with simple custom entity `Brand` (like in the example).
I added `validation.yml` file with this content in this directory `Acme/Bundle/MyBundle/Resources/config/` :

``` yml
Acme\Bundle\MyBundle\Entity\Brand:
    properties:
        label:
            - NotBlank: ~
        code:
            - NotBlank: ~
```

But saving an entity with an empty field generates an error in the logs and the error is not raised on front:

```
request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid data" at /var/www/steam-pim/src/vendor/akeneo-labs/custom-entity-bundle/Action/Rest/UpdateAction.php line 54 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): Invalid data at /var/www/steam-pim/src/vendor/akeneo-labs/custom-entity-bundle/Action/Rest/UpdateAction.php:54)"}
```
How can add clean validation on my entity?

Thank you!
Simon
