### ISSUE TITLE
compatibility issue with 2.2

### ISSUE THREAD

**Issue by eltjor** [akeneo-labs/CustomEntityBundle#156]
PIM-6367: Rename service pim_enrich.query.product_and_product_model_query_builder_factory into pim_catalog.query.product_and_product_model_query_builder_factory

```
    pim_custom_entity.event_subscriber.check_reference_data_on_removal:
        class: '%pim_custom_entity.event_subscriber.check_reference_data_on_removal.class%'
        arguments:
            - '@pim_custom_entity.repository.attribute'
            - '@pim_catalog.query.product_and_product_model_query_builder_factory'
            - '@pim_custom_entity.configuration.registry'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_subscriber }
```
