### ISSUE TITLE
Select field type for non custom entities

### ISSUE THREAD

**Issue by davibennun** [akeneo-labs/CustomEntityBundle#185]
Hey guys,

I am using this bundle to create a custom module for akeneo.
On my create modal I need a select field so users can select an attribute entity.
Is there a built-in module for that? I looked into custom_entity/field/select2 but looks like it doesn't do the job, unless I am missing something.

Bellow is my create.yml

```
extensions:
    pim-myentity-create-modal:
        .....
    pim-myentity-create-attribute:
        module: custom_entity/field/select2
        parent: pim-myentity-create-modal
        targetZone: fields
        position: 20
        config:
            fieldName: attribute
            choiceNameField: code
            choiceValueField: name
            isCustomEntity: false
            entityName: attribute
            required: true
```

Thank you
