### ISSUE TITLE
Not required elements appears as required in production environnement

### ISSUE THREAD

**Issue by manuscle** [akeneo-labs/CustomEntityBundle#84]
Hi,
For a Color entity, i changed the color.orm.yml schema, then updated database and cleared cache. But i still get all elements required in production env. It's working fine in dev env ...

```
My\Bundle\AppBundle\Entity\Color:
    repositoryClass: Pim\Bundle\CustomEntityBundle\Entity\Repository\CustomEntityRepository
    type: entity
    table: my_reference_data_color
    changeTrackingPolicy: DEFERRED_EXPLICIT
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            unique: true
        sortOrder:
            type: integer
        name:
            type: string
            length: 255
        hex:
            type: string
            length: 255
            nullable: true
        red:
            type: integer
            nullable: true
        green:
            type: integer
            nullable: true
        blue:
            type: integer
            nullable: true
        ral:
            type: integer
            unique: true
            nullable: true
    lifecycleCallbacks: {  }

```
